<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>TextInOutUtils</name>
    <message>
        <location filename="../TextInOutUtils.py" line="235"/>
        <source>Test stopped on failure of rule: {ruleString}</source>
        <translation>Prueba detenida debido a un error en la regla: {ruleString}</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="327"/>
        <source>Run the {wildebeest} cleanup tool</source>
        <translation>Ejecutar la herramienta de limpieza {wildebeest}</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="328"/>
        <source>help</source>
        <translation>ayuda</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="526"/>
        <source>Test stopped on failure of rule {ruleNumber}: {ruleString}</source>
        <translation>Prueba detenida debido a un error en la regla {ruleNumber}: {ruleString}</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="695"/>
        <source>Invalid File</source>
        <translation>Archivo inválido</translation>
    </message>
    <message>
        <location filename="../TextInOutUtils.py" line="713"/>
        <source>Invalid Rules File</source>
        <translation>Archivo de reglas inválido</translation>
    </message>
</context>
</TS>
