<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>RuleAssistant</name>
    <message>
      <location filename="../RuleAssistant.py" line="118"/>
      <source>Rule Assistant</source>
      <translation>Asistente de reglas</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="89"/>
        <source>This module runs the Rule Assistant tool which let&apos;s you create transfer rules.</source>
        <translation>Este módulo ejecuta la herramienta Rule Assistant, que le permite crear reglas de transferencia.</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="93"/>
        <source>Runs the Rule Assistant tool.</source>
        <translation>Ejecuta la herramienta Rule Assistant.</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="333"/>
        <source>Compiled bilingual dictionary not found. Run the &quot;Run Apertium&quot; module to display test data in the Rule Assistant.</source>
        <translation>No se encontró el diccionario bilingüe compilado. Ejecute el módulo &quot;Run Apertium&quot; para mostrar datos de prueba en el Rule Assistant.</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="345"/>
        <source>The text named &apos;%s&apos; was not found.</source>
        <translation>No se encontró el texto llamado '%s'.</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="413"/>
        <source>&lt;html&gt;&lt;body&gt;&lt;p&gt;No test data available.&lt;/body&gt;&lt;/html&gt;
</source>
        <translation>&lt;html&gt;&lt;body&gt;&lt;p&gt;No hay datos de prueba disponibles.&lt;/body&gt;&lt;/html&gt;
</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="443"/>
        <source>An error happened when running the Rule Assistant tool: {e.output.decode(&quot;utf-8&quot;)}</source>
        <translation>Ocurrió un error al ejecutar la herramienta Rule Assistant: {e.output.decode(&quot;utf-8&quot;)}</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="497"/>
        <source>No rules created.</source>
        <translation>No se crearon reglas.</translation>
    </message>
    <message>
        <location filename="../RuleAssistant.py" line="374"/>
        <source>&lt;p&gt;&lt;b&gt;Source Text:&lt;/b&gt; </source>
        <translation>&lt;p&gt;&lt;b&gt;Texto fuente:&lt;/b&gt; </translation>
    </message>
</context>
</TS>
